### PR TITLE
Bump acorn from 5.7.3 to 5.7.4

### PR DESCRIPTION
**Pull request by meghnasavit**
Bumps [acorn](https://github.com/acornjs/acorn) from 5.7.3 to 5.7.4.
- [Release notes](https://github.com/acornjs/acorn/releases)
- [Commits](https://github.com/acornjs/acorn/compare/5.7.3...5.7.4)

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Comment by meghnasavit** [comment]
ffddddd

**Comment by meghnasavit** [comment]
dcxczxzzx

**Comment by meghnasavit** [comment]
vvvvxxxx

**Comment by meghnasavit** [comment]
dddddddd

**Comment by anaghasavit** [comment]
hi

**Comment by anaghasavit** [comment]
abcdef

**Review by anaghasavit — CHANGES_REQUESTED** [review]
_hi_

**Review by anaghasavit — APPROVED** [review]

**Comment by meghnasavit** [comment]
Comment to check attachment colour

**Pull request merged**
